z# -*- coding: utf-8 -*-
"""Copy of PotatoDiseaseClassification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1maAUV1vIYC856PCSzvIp0nkFs0bJUiwa
"""

import tensorflow as tf
from tensorflow.keras import models, layers
import matplotlib.pyplot as plt
import numpy as np
from tensorflow.keras.preprocessing.image import ImageDataGenerator

IMAGE_SIZE = 256
CHANNELS = 3
BATCH_SIZE = 32
EPOCHS = 70

DATASET_PATH = "/content/drive/MyDrive/Colab Notebooks/potato-disease"

# -----------------------------
# DATA GENERATORS
# -----------------------------

train_datagen = ImageDataGenerator(
    rescale=1./255,
    rotation_range=10,
    horizontal_flip=True
)

validation_datagen = ImageDataGenerator(rescale=1./255)

test_datagen = ImageDataGenerator(rescale=1./255)

train_generator = train_datagen.flow_from_directory(
    f"{DATASET_PATH}/train",
    target_size=(IMAGE_SIZE, IMAGE_SIZE),
    batch_size=BATCH_SIZE,
    class_mode="sparse"
)

validation_generator = validation_datagen.flow_from_directory(
    f"{DATASET_PATH}/val",
    target_size=(IMAGE_SIZE, IMAGE_SIZE),
    batch_size=BATCH_SIZE,
    class_mode="sparse"
)

test_generator = test_datagen.flow_from_directory(
    f"{DATASET_PATH}/test",
    target_size=(IMAGE_SIZE, IMAGE_SIZE),
    batch_size=BATCH_SIZE,
    class_mode="sparse"
)

# -----------------------------
# CLASS NAMES
# -----------------------------

class_names = list(train_generator.class_indices.keys())
print("Classes:", class_names)

# -----------------------------
# MODEL
# -----------------------------

input_shape = (IMAGE_SIZE, IMAGE_SIZE, CHANNELS)
n_classes = len(class_names)

model = models.Sequential([
    layers.InputLayer(input_shape=input_shape),

    layers.Conv2D(32, (3,3), activation='relu'),
    layers.MaxPooling2D((2,2)),

    layers.Conv2D(64, (3,3), activation='relu'),
    layers.MaxPooling2D((2,2)),

    layers.Conv2D(64, (3,3), activation='relu'),
    layers.MaxPooling2D((2,2)),

    layers.Conv2D(64, (3,3), activation='relu'),
    layers.MaxPooling2D((2,2)),

    layers.Conv2D(64, (3,3), activation='relu'),
    layers.MaxPooling2D((2,2)),

    layers.Conv2D(64, (3,3), activation='relu'),
    layers.MaxPooling2D((2,2)),

    layers.Flatten(),
    layers.Dense(64, activation='relu'),
    layers.Dropout(0.3),
    layers.Dense(n_classes, activation='softmax')
])

model.summary()

# -----------------------------
# COMPILE
# -----------------------------

model.compile(
    optimizer='adam',
    loss=tf.keras.losses.SparseCategoricalCrossentropy(),
    metrics=['accuracy']
)

# -----------------------------
# HANDLE CLASS IMBALANCE
# -----------------------------

class_weight = {
    0:1,
    1:1,
    2:5
}

# -----------------------------
# TRAIN
# -----------------------------

history = model.fit(
    train_generator,
    validation_data=validation_generator,
    epochs=EPOCHS,
    class_weight=class_weight
)

# -----------------------------
# EVALUATE
# -----------------------------

scores = model.evaluate(test_generator)
print("Test Accuracy:", scores[1])

# -----------------------------
# PLOT TRAINING
# -----------------------------

acc = history.history['accuracy']
val_acc = history.history['val_accuracy']
loss = history.history['loss']
val_loss = history.history['val_loss']

plt.figure(figsize=(10,5))

plt.subplot(1,2,1)
plt.plot(acc,label="Train Accuracy")
plt.plot(val_acc,label="Validation Accuracy")
plt.legend()
plt.title("Accuracy")

plt.subplot(1,2,2)
plt.plot(loss,label="Train Loss")
plt.plot(val_loss,label="Validation Loss")
plt.legend()
plt.title("Loss")

plt.show()

# -----------------------------
# TEST PREDICTION
# -----------------------------

for image_batch, label_batch in test_generator:

    first_image = image_batch[0]
    first_label = int(label_batch[0])

    plt.imshow(first_image)
    plt.title("Actual: "+class_names[first_label])
    plt.show()

    prediction = model.predict(image_batch)

    predicted_class = class_names[np.argmax(prediction[0])]
    print("Predicted:", predicted_class)

    break

# -----------------------------
# SAVE MODEL
# -----------------------------

model.save("/content/drive/MyDrive/Colab Notebooks/models/1.keras")

print("Model saved successfully as 1.keras")

import numpy as np
from tensorflow.keras.preprocessing import image

img_path = "/content/drive/MyDrive/Colab Notebooks/potato-disease/test/Potato___Late_blight/2e18248f-e251-44c0-b9a5-a198455f43ee___RS_LB 4858.JPG"

img = image.load_img(img_path, target_size=(256,256))

img_array = image.img_to_array(img) / 255.0
img_array = np.expand_dims(img_array, axis=0)

pred = model.predict(img_array)

print("Predicted:", class_names[np.argmax(pred)])
print("Confidence:", np.max(pred))